export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";
export const GOOGLE_SIGN_OUT_SUCCESS = "GOOGLE_SIGN_OUT_SUCCESS";
export const GOOGLE_SIGN_OUT_FAIL = "GOOGLE_SIGN_OUT_FAIL";

export const FETCH_ALL_POST_SUCCESS = "FETCH_ALL_POST_SUCCESS";
export const FETCH_ALL_POST_FAIL = "FETCH_ALL_POST_FAIL";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const GET_USER_INFO = "GET_USER_INFO";